__version__ = "1.4.6"

__changelog__ = {
    "1.4.6": [
        "Audit: structured `audit()` event helper + LOG_FORMAT=json for SIEM/aggregator-friendly output",
        "Audit: vote_cast / vote_changed log every vote with username, clientId, value, prior value, IP",
        "Audit: round_revealed logs vote map, average, median, outliers, and new consensus flag",
        "Audit: countdown_started / countdown_cancelled, round_started (was 'new round') with round counter",
        "Audit: user_joined with role (host/user/spectator), user_reconnected distinct from user_joined",
        "Audit: user_disconnected (immediate) and user_left (after 2s grace) as distinct events",
        "Audit: session_ended on cleanup with reason, duration, round_count, total_votes",
        "Audit: host actions logged — deck_changed (with IP), host_voting_decision, voting_locked/unlocked",
        "State: per-session roundCount + totalVotes counters for end-of-session summary",
        "Plumbing: isSpectator flag tracked server-side (enforcement lands with Phase 8 Spectator Mode UI)",
    ],
    "1.4.5": [
        "CI: GitHub Actions workflow runs ruff + black (Python) and prettier + eslint (JS) on every push/PR to main",
        "Tooling: pyproject.toml with ruff (isort, bugbear, pyupgrade) + black (line-length 100)",
        "Tooling: package.json with eslint flat config + prettier (dev-only, no build step)",
        "Formatting: normalized all JS/CSS/HTML/MD via prettier (2-space indent, single quotes, trailing commas)",
        "Formatting: normalized Python via black + ruff --fix (import sort, trailing newlines)",
    ],
    "1.4.4": [
        "Correctness: late joiners at reveal state now receive revealVotes + user chips; cards disabled",
        "Reliability: graceful shutdown broadcasts serverShutdown event before closing sockets",
        "Reliability: /health now reports per-background-task liveness (session/rate-limit/log cleanup)",
        "Observability: X-Request-ID middleware with contextvars-backed trace ID in every log line",
        "UI: global error boundary surfaces uncaught errors + unhandled rejections via toast",
        "Build: /changelog.html now server-rendered from version.py (single source of truth)",
        "Deps: requirements.txt tilde-pinned (~=X.Y.Z) for reproducible installs",
        "Tooling: .editorconfig for consistent indentation across editors",
        "Docs: README badges, architecture mermaid diagram, polished language",
    ],
    "1.4.3": [
        "Correctness: actionFailed event for non-join rejections (host-only, rate-limit) — no redirect loop",
        "Correctness: countdown state synced to mid-countdown joiners (rejoin shows remaining time)",
        "Correctness: countdownTask stored + cancelled defensively on new round",
        "Correctness: revealed flag reset defensively in changeDeck / setVotingEnabled",
        "Correctness: last_create_time prune cutoff 30min → 1min (matches 3s cooldown)",
        "Correctness: upper-median documented for even vote counts (ordinal-safe, no interpolation)",
        "Correctness: requestNewRound rate-limit comment fixed (was '3/hr', actual 30/hr)",
        "Cleanup: removed unused DECK_VALUE_MIN/MAX and DECK_SIZE_MIN/MAX constants",
    ],
    "1.4.2": [
        "Security: self-hosted socket.io client, dropped jsdelivr from CSP",
        "Security: connect-src CSP narrowed in production (no localhost origins)",
        "Security: fail-loud on CORS_ORIGINS=* with credentials in production",
        "Security: removed deprecated X-XSS-Protection header",
        "Security: session ID now uses full token_urlsafe(12) length (dropped redundant slice)",
        "Security: username regex broadened to unicode letters/digits/spaces with control-char stripping",
        "Security: Socket.IO cors_allowed_origins now locked to CORS_ORIGINS",
        "Security: /create switched from GET to POST (303 redirect) to avoid prefetch state change",
        "Security: join handler no longer reads client-supplied asgi.scope for IP — uses server-stored map",
        "PROXY_DEPTH env var for multi-proxy X-Forwarded-For parsing (default last-hop)",
        "Rate-limit tracking dicts bounded via MAX_RATE_LIMIT_ENTRIES with oldest-first eviction",
        "LOG_RETENTION_DAYS env var (default 30) with background cleanup of rotated log files",
        "Version badge styles moved from inline <style> block to public/css/version-badge.css",
    ],
    "1.4.1": [
        "Clickable version badge opens full changelog page in new tab",
        "Full version history: changelogs for all versions from 1.0.0 to current",
        "Rate limit IP whitelist via RATE_LIMIT_WHITELIST environment variable",
        "Socket reconnect: auto-rejoin with preserved vote state, connection status indicator",
        "Toast notifications: join, leave, deck change, connection restored, link copied",
        "Deck change toast shows friendly deck name",
        "User list revamp: voted/pending/spectator states, vote count, live status row",
        "Playing-card redesign: corner values, gradient depth, hover/select lift",
        "Revealed vote cards: bigger, corner values, outlier glow, names wrap below card",
        "Stat tiles: Average, Median, Votes count, Consensus celebration or Outlier count",
        "Card flip animation on reveal; confetti on unanimous consensus",
        "User leave grace period (2s) prevents false leaves on reconnect",
    ],
    "1.4.0": [
        "Host session settings modal: sliders for join voting and start voting enabled",
        "Host can lock/unlock voting from the game UI (only when no votes cast)",
        "Locked voting: cards disabled with lock indicator for all users",
        "Post-reveal lock scheduling: host can schedule lock change for next round",
        "All host controls disabled during countdown to prevent race conditions",
        "New Session button redesigned from link to button with disabled state",
        "In-place re-vote: Start New Round resets votes without redirect or new session",
        "Host vote decision now scoped per-session to prevent modal skip across sessions",
    ],
    "1.3.2": [
        "Fix rate limiting: reduce create session cooldown from 10s to 3s",
        "Fix rate limiting: increase new round limit from 3/hour to 30/hour",
        "Dependencies: update all packages to latest, remove unused shortuuid",
    ],
    "1.3.1": [
        "Version tooltip now shows last 2 versions' changelogs",
        "Fixed changelog not appearing on game page",
    ],
    "1.3.0": [
        "Koningsdag theme: crown decoration, falling Dutch flags, orange color scheme",
        "Audit logging with file rotation (5MB, 3 backups)",
        "Username persistence via localStorage with modal prefill",
        "Deck presets: Fibonacci, Hours, T-shirt sizes with host-only switching",
        "Host-left notification: overlay when host disconnects",
        "Version tooltip: hover version badge to see changelog",
        "Security: crypto-secure client IDs, removed CSP unsafe-inline",
        "Security: proxy-aware IP detection, timezone-aware rate limiting",
        "Bug fixes: session ID message, noscript text, outlier colors, default deck",
    ],
    "1.2.0": [
        "Christmas theme with configurable decorations and snow particles",
        "Monitoring endpoints and Socket.IO rate limiting",
        "Performance and accessibility improvements",
    ],
    "1.1.0": [
        "Fibonacci sequence as default voting deck",
        "Outlier detection: flag votes by Fibonacci step-distance from median",
        "Reuse client deck selection across rounds",
        "16-character cryptographically secure session IDs",
        "Per-IP rate limiting and input validation",
        "Resource limits: max sessions, users per session, username length",
    ],
    "1.0.0": [
        "Initial release: real-time planning poker with FastAPI + Socket.IO",
        "Host controls: exclude self from voting, request new round",
        "Question mark vote option for abstaining",
        "Vote average and outlier highlighting after reveal",
        "User list with live presence tracking",
        "Session timeouts with automatic cleanup",
        "Basic per-IP rate limiting for session creation",
        "Username limited to 20 characters",
    ],
}
